import {
  aliasesTrace,
  ownershipTrace,
  rowsTrace,
  reallocTrace,
} from "./traces/memory.js";
import {
  linkedTrace,
  doublyTrace,
  circularQueueTrace,
  linkedQueueTrace,
} from "./traces/structures.js";
import { postfixTrace, evaluateTrace } from "./traces/expressions.js";
import {
  traversalTrace,
  treeHeightTrace,
  treeSumTrace,
  bstDeleteTrace,
  freeTreeTrace,
  avlTrace,
} from "./traces/trees.js";
import {
  heapTrace,
  hashTrace,
  chainingTrace,
  trieTrace,
} from "./traces/indexed.js";
import {
  factorialTrace,
  hanoiTrace,
  permutationTrace,
  floodTrace,
} from "./traces/recursion.js";
import {
  sortTrace,
  mergeTrace,
  partitionTrace,
  binarySearchTrace,
} from "./traces/sorting.js";
import {
  loopTrace,
  recurrenceTrace,
  timingTrace,
  baseTrace,
  bitsTrace,
} from "./traces/reasoning.js";

export const groups = [
  "C & memory",
  "Linear structures",
  "Trees & indexed structures",
  "Recursion & algorithms",
  "Analysis & representation",
];
const preset = (label, build) => ({ label, build });
const question = (prompt, answer, distractor, explanation) => ({
  prompt,
  choices: [answer, distractor],
  answer: 0,
  explanation,
});
const lesson = (
  id,
  group,
  title,
  objective,
  prerequisite,
  invariant,
  complexity,
  mistake,
  presets,
  checkpoint,
) => ({
  id,
  group,
  title,
  objective,
  prerequisite,
  invariant,
  complexity,
  mistake,
  presets,
  checkpoint,
});
const catalog = [
  lesson(
    "aliases",
    0,
    "Pointers & arrays",
    "Separate pointer movement from writes through a pointer.",
    "Array indexing and C assignment.",
    "Aliases reference the same storage; pointer arithmetic counts elements.",
    "Constant work for this fixed example; traversing n slots takes Θ(n).",
    "Incrementing p changes an address, not the integer at *p.",
    [preset("Two aliases", aliasesTrace)],
    question(
      "After p++ and *q = 14, what does *p read?",
      "14",
      "12",
      "Both p and q address values[1]. The write changed that shared slot.",
    ),
  ),
  lesson(
    "ownership",
    0,
    "Structs & shallow copies",
    "Track separate struct and character allocations through cleanup.",
    "Pointers, structs, malloc, and free.",
    "Each live allocation is freed exactly once, after its last use.",
    "Allocation cost is allocator-dependent; this trace uses a fixed number of allocations.",
    "Copying a pointer field does not copy the pointed-to buffer.",
    [preset("Shared name buffer", ownershipTrace)],
    question(
      "How many character buffers exist after b->name = a->name?",
      "One",
      "Two",
      "The assignment copies an address. Freeing both name fields would free the same allocation twice.",
    ),
  ),
  lesson(
    "rows",
    0,
    "2D & ragged arrays",
    "Follow two levels of indirection and free rows in a safe order.",
    "Pointers to pointers and sizeof.",
    "The outer array stays live until each separately allocated row has been freed.",
    "For r rows and s total slots, initialization takes Θ(r+s) work; freeing visits r rows.",
    "An int** allocation is not automatically one contiguous rectangular matrix.",
    [
      preset("Equal row lengths", () => rowsTrace()),
      preset("Ragged lengths", () => rowsTrace(true)),
    ],
    question(
      "Which allocation must be freed last?",
      "The outer row-pointer array",
      "The first row",
      "The outer array holds the addresses needed to free all the rows.",
    ),
  ),
  lesson(
    "resize",
    0,
    "Safe realloc",
    "Keep the owner on failure and invalidate old aliases on a moving resize.",
    "malloc, free, and pointer-to-pointer parameters.",
    "Assign the new owner only after realloc succeeds. This example uses a positive requested size.",
    "A resize may copy n existing elements: do not assume constant time.",
    "Assigning realloc directly to the owner can lose the original buffer on failure.",
    [
      preset("Moving success", () => reallocTrace()),
      preset("Simulated failure", () => reallocTrace(true)),
    ],
    question(
      "What happens to the original allocation if realloc returns NULL here?",
      "It remains allocated",
      "It is freed",
      "For a nonzero requested size, allocation failure leaves the original buffer unchanged.",
    ),
  ),
  lesson(
    "list",
    1,
    "Singly linked lists",
    "Insert, delete, and reverse without losing the unprocessed suffix.",
    "Struct pointers and heap ownership.",
    "During reversal, prev owns the reversed prefix and cur the untouched suffix.",
    "Front insertion/deletion Θ(1); reversal Θ(n) time and Θ(1) extra space.",
    "Save next before rewriting cur->next, and assign returned heads at the caller.",
    [
      preset("Reverse three nodes", () => linkedTrace()),
      preset("Reverse empty list", () => linkedTrace("reverse", true)),
      preset("Insert at front", () => linkedTrace("insert")),
      preset("Delete front", () => linkedTrace("delete")),
      preset("Delete empty list", () => linkedTrace("delete", true)),
    ],
    question(
      "Why save cur->next before changing the link?",
      "To keep the remaining suffix reachable",
      "To allocate another node",
      "Once cur->next points backward, its old successor would otherwise be lost.",
    ),
  ),
  lesson(
    "doubly",
    1,
    "Doubly linked lists",
    "Repair both directions when inserting a new head.",
    "Singly linked list insertion.",
    "For neighboring live nodes, next and prev agree; the head has prev = NULL.",
    "Front insertion Θ(1).",
    "Updating only next leaves a broken backward chain.",
    [
      preset("Nonempty head", () => doublyTrace()),
      preset("Empty head", () => doublyTrace(true)),
    ],
    question(
      "Which old-node field changes when inserting before a nonempty head?",
      "The old head’s prev",
      "The old head’s next",
      "The old head now has NEW as its predecessor. Its next remains unchanged.",
    ),
  ),
  lesson(
    "postfix",
    1,
    "Infix → postfix",
    "Use a stack to delay operators while preserving evaluation order.",
    "Stack push/pop and operator precedence.",
    "Only pending operators remain on the stack; operands go directly to output.",
    "Θ(n) time and O(n) stack space: each operator is pushed and popped at most once.",
    "Parentheses are boundaries, not tokens in the final postfix expression.",
    [
      preset("Precedence", () => postfixTrace()),
      preset("Parentheses", () => postfixTrace(true)),
    ],
    question(
      "Why is multiplication emitted before the pending addition?",
      "It has higher precedence",
      "It appeared later so it always goes first",
      "Precedence determines when an operator is popped; equal precedence in this example is left-associative.",
    ),
  ),
  lesson(
    "evaluation",
    1,
    "Postfix evaluation",
    "Pop right before left and replace two operands with a result.",
    "Stacks and integer arithmetic.",
    "A valid completed expression leaves one value on the stack.",
    "Θ(n) time, O(n) worst-case stack space.",
    "For subtraction, first popped − second popped reverses the operands.",
    [preset("(8−3)×2", evaluateTrace)],
    question(
      "For postfix 83−, which value is the right operand?",
      "3",
      "8",
      "The top value is popped first, but it belongs on the right of the operator.",
    ),
  ),
  lesson(
    "queue",
    1,
    "Circular queues",
    "Separate physical slots from logical FIFO order.",
    "Arrays, remainder, and queue operations.",
    "0 ≤ count ≤ capacity; head is next removal and tail is next insertion.",
    "Enqueue/dequeue Θ(1), fixed Θ(capacity) storage.",
    "head == tail can mean full or empty; count disambiguates. Removed bytes may remain in unused slots.",
    [
      preset("Wrap & full guard", () => circularQueueTrace()),
      preset("Drain & empty guard", () => circularQueueTrace(true)),
    ],
    question(
      "Can head == tail represent a full queue?",
      "Yes, if count equals capacity",
      "No, it always means empty",
      "The count-based implementation can use every slot without confusing full and empty.",
    ),
  ),
  lesson(
    "linked-queue",
    1,
    "Linked queue endpoints",
    "Handle removing the last node without leaving a stale back pointer.",
    "Linked lists and pointer-to-pointer parameters.",
    "An empty queue has both front and back equal to NULL.",
    "Dequeue Θ(1); linked enqueue with a tail pointer is also Θ(1).",
    "Only clearing front leaves back pointing at freed storage.",
    [preset("Remove last node", linkedQueueTrace)],
    question(
      "When the final node is removed, what must back become?",
      "NULL",
      "The freed node’s address",
      "Both endpoints must reflect the empty queue before the node is freed.",
    ),
  ),
  lesson(
    "traversal",
    2,
    "Tree traversals",
    "Locate the visit statement relative to the two recursive calls.",
    "Recursive base cases and binary tree links.",
    "Each subtree finishes its own visit order before control returns to its parent.",
    "Θ(n) time, O(h) call stack; a skewed tree can have h=n−1.",
    "Inorder is sorted only for a valid BST, not every binary tree.",
    [
      preset("Inorder", () => traversalTrace()),
      preset("Preorder", () => traversalTrace("preorder")),
      preset("Postorder", () => traversalTrace("postorder")),
    ],
    question(
      "Which traversal emits a parent after both children?",
      "Postorder",
      "Preorder",
      "Postorder places the visit after both recursive calls. It is useful for bottom-up work and cleanup.",
    ),
  ),
  lesson(
    "height",
    2,
    "Recursive tree height",
    "Combine child results when their calls return.",
    "Tree traversal and local variables in recursive frames.",
    "The result is 1 + max(left height, right height); here NULL = −1.",
    "Θ(n) time, O(h) call stack.",
    "Height conventions differ: state whether height counts edges or nodes.",
    [preset("Height in edges", treeHeightTrace)],
    question(
      "Under this convention, what is a leaf’s height?",
      "0",
      "1",
      "Its two NULL children return −1, so 1 + max(−1,−1) = 0.",
    ),
  ),
  lesson(
    "tree-sum",
    2,
    "Recursive subtree sums",
    "Combine complete child results with the current node’s value.",
    "Tree traversal and recursive return values.",
    "An empty subtree contributes zero; each live node contributes exactly once.",
    "Θ(n) time and O(h) recursive stack space.",
    "The child result is a subtree total, not just the child’s own value.",
    [preset("Sum six nodes", treeSumTrace)],
    question(
      "What should an empty subtree return when summing values?",
      "0",
      "1",
      "Zero adds no value. The base-case identity depends on the operation being computed.",
    ),
  ),
  lesson(
    "bst-delete",
    2,
    "BST deletion",
    "Reconnect returned roots and replace two-child keys with an inorder successor.",
    "BST ordering, recursion, and free.",
    "Ordering applies to entire subtrees. Node identity is separate from its key.",
    "O(h) time; O(log n) only when height stays logarithmic, otherwise O(n).",
    "Never read successor->value after freeing successor; save/copy it first.",
    [
      preset("Two children", () => bstDeleteTrace()),
      preset("Leaf", () => bstDeleteTrace("leaf")),
      preset("One child", () => bstDeleteTrace("one child")),
    ],
    question(
      "Why choose the right subtree’s minimum as successor?",
      "It is the next larger key",
      "It is always the deepest leaf",
      "The successor fits between the original left subtree and the remaining right subtree.",
    ),
  ),
  lesson(
    "tree-free",
    2,
    "Postorder cleanup",
    "Release children before the parent allocation.",
    "Tree recursion and memory ownership.",
    "Every node remains live until the child pointers needed from it have been followed.",
    "Θ(n) time and O(h) call stack.",
    "free(root) does not recursively free descendants or clear the caller’s pointer.",
    [preset("Release six nodes", freeTreeTrace)],
    question(
      "Why can’t free(root) come before the recursive calls?",
      "Child links would be read from freed memory",
      "free automatically releases the children",
      "The program still needs root->left and root->right. Reading either after free is invalid.",
    ),
  ),
  lesson(
    "heap",
    2,
    "Min-heaps",
    "Connect array indices to tree shape and follow one repair path.",
    "Complete binary trees and array indexing.",
    "Parent ≤ children, with no gaps in the complete-tree shape.",
    "Insert/delete O(log n); bottom-up heapify Θ(n); root lookup Θ(1).",
    "A heap array is not fully sorted, and heap order is not BST order.",
    [
      preset("Bottom-up heapify", () => heapTrace()),
      preset("Insert minimum", () => heapTrace("insert")),
      preset("Delete minimum", () => heapTrace("delete")),
    ],
    question(
      "Why is bottom-up heapify linear rather than n log n?",
      "Most nodes have short repair paths",
      "Every node moves to the root",
      "Summing node counts times remaining subtree height gives Θ(n); repeated insertion has a different bound.",
    ),
  ),
  lesson(
    "hash",
    2,
    "Open-addressed hashing",
    "Follow collisions and preserve probe paths through deletion.",
    "Remainder and fixed arrays.",
    "Insertion and lookup use the same probe sequence; EMPTY stops search, DELETED does not.",
    "Expected O(1) with suitable hashing/load; worst-case O(n). Quadratic probing may not visit all slots.",
    "Deleting to EMPTY can make an existing colliding key unreachable.",
    [
      preset("Linear probing", () => hashTrace()),
      preset("Linear + tombstone", () => hashTrace("linear", true)),
      preset("Quadratic probing", () => hashTrace("quadratic")),
    ],
    question(
      "Should lookup stop at a tombstone?",
      "No, continue probing",
      "Yes, the key is absent",
      "A later key may have passed this slot before the deletion. Only a never-used slot ends that search.",
    ),
  ),
  lesson(
    "chaining",
    2,
    "Separate chaining",
    "Search a bucket’s linked chain instead of probing adjacent slots.",
    "Linked lists and a hash function.",
    "Every node in a chain belongs to that bucket.",
    "Expected O(1+α), α=n/buckets; worst-case O(n).",
    "Hashing does not guarantee constant time when many keys collide.",
    [preset("Three colliding keys", chainingTrace)],
    question(
      "Where does lookup go after a collision in chaining?",
      "To the next node in that bucket",
      "To the next array bucket",
      "The bucket points to a linked chain. Adjacent table slots belong to other hash values.",
    ),
  ),
  lesson(
    "avl",
    2,
    "AVL rotations",
    "Repair balance without changing inorder key order.",
    "BST ordering and subtree heights.",
    "Each node’s child heights differ by at most one after repair.",
    "Search/insert/delete O(log n) in a maintained AVL tree; each rotation Θ(1).",
    "Update the old root’s height before the new root; deletion can need repairs at multiple ancestors.",
    [
      ...["LL", "RR", "LR", "RL"].map((k) =>
        preset(`${k} insertion case`, () => avlTrace(k)),
      ),
      preset("Deletion, child balance 0", () => avlTrace("deletion")),
    ],
    question(
      "What must a rotation preserve?",
      "The inorder sequence",
      "The original root",
      "Links and roots change, but all keys must remain in BST order.",
    ),
  ),
  lesson(
    "trie",
    2,
    "Tries: words & prefixes",
    "Share character paths while marking complete words separately.",
    "Character indexing and zero-initialized structs.",
    "A terminal flag records word membership; a path can exist without being terminal.",
    "Lookup/insert O(L) for L letters with a fixed alphabet; storage depends on allocated prefix nodes.",
    "This implementation accepts only lowercase a–z; arbitrary characters require validation.",
    [
      preset("Existing prefix, absent word", () => trieTrace()),
      preset("Missing edge", () => trieTrace(true)),
    ],
    question(
      "If car is stored, does the path ca mean ca is a stored word?",
      "No, its terminal flag must be set",
      "Yes, every prefix is a word",
      "Prefixes share paths, but word membership is explicit.",
    ),
  ),
  lesson(
    "factorial",
    3,
    "Recursion: call & return",
    "Follow separate stack frames and the values passed back during unwinding.",
    "Functions, local variables, and unsigned arithmetic.",
    "Each non-base call waits for n−1; the base case returns 1.",
    "Θ(n) time and Θ(n) stack space, within representable arithmetic and stack limits.",
    "The return phase does the multiplication. Large factorials overflow C integer types.",
    [
      preset("factorial(4)", () => factorialTrace()),
      preset("Base case", () => factorialTrace(true)),
    ],
    question(
      "When is n * child evaluated?",
      "After the child returns",
      "Before the recursive call",
      "The caller is suspended until its recursive call supplies child.",
    ),
  ),
  lesson(
    "hanoi",
    3,
    "Tower of Hanoi",
    "Track changing parameter roles and a recurrence with two recursive calls.",
    "Recursion and legal disk moves.",
    "A smaller disk always lies above a larger disk on each peg.",
    "2ⁿ−1 moves, Θ(2ⁿ) time, O(n) recursive depth.",
    "Both child calls move n−1 disks, but their peg roles differ.",
    [preset("Three disks", hanoiTrace)],
    question(
      "What recurrence counts the moves?",
      "T(n)=2T(n−1)+1",
      "T(n)=T(n−1)+1",
      "Move a smaller tower away, move the largest disk, then move the smaller tower onto it.",
    ),
  ),
  lesson(
    "permutations",
    3,
    "Backtracking permutations",
    "Choose, recurse, then restore before exploring a sibling branch.",
    "Recursive frames and swapping characters.",
    "The prefix is fixed; restoration leaves the caller’s word unchanged.",
    "n! leaves for distinct characters; materializing every length-n output takes Θ(n·n!).",
    "Omitting the undo step changes the starting state of later branches.",
    [preset("Three distinct letters", permutationTrace)],
    question(
      "Why swap back after the recursive call?",
      "To restore the state for the next choice",
      "To sort the letters",
      "Sibling branches must start from the same prefix and suffix state.",
    ),
  ),
  lesson(
    "flood",
    3,
    "Flood fill",
    "Prevent repeated visits and separate reachable from disconnected cells.",
    "2D array bounds and recursion.",
    "A visited cell is marked before exploring neighbors.",
    "O(rows·columns) time and worst-case stack space for a full region.",
    "Test bounds before indexing; mark visited before recurring, not after.",
    [preset("Four-way connected region", floodTrace)],
    question(
      "When should a reachable cell be marked visited?",
      "Before visiting neighbors",
      "After every neighbor returns",
      "Two adjacent cells would otherwise keep calling each other before either becomes visited.",
    ),
  ),
  lesson(
    "search",
    3,
    "Binary search",
    "Shrink a sorted candidate interval until found or empty.",
    "Sorted arrays and integer division.",
    "If present, target lies inside inclusive [lo,hi].",
    "O(log n) time, O(1) space in this iterative implementation.",
    "Use mid±1 to make progress; a match does not guarantee the first occurrence.",
    [
      preset("Found target", () => binarySearchTrace()),
      preset("Missing target", () => binarySearchTrace(true)),
    ],
    question(
      "Why set lo = mid + 1 when a[mid] < target?",
      "Midpoint and smaller values are ruled out",
      "To keep midpoint for another comparison",
      "Sorted order excludes all indices up to mid and guarantees interval progress.",
    ),
  ),
  lesson(
    "simple-sorts",
    3,
    "Insertion, selection & bubble",
    "Compare shifting, choosing a minimum, and exchanging neighbors.",
    "Array indexing, loops, and comparisons.",
    "Insertion sorts a prefix; selection finalizes a prefix; bubble finalizes a suffix.",
    "Insertion/bubble: Θ(n) best, Θ(n²) average/worst. Selection: Θ(n²) comparisons in all cases. All use O(1) extra space.",
    "Insertion saves key while shifting; a bubble early-exit requires a whole pass with no swaps.",
    ["insertion", "selection", "bubble"].flatMap((m) => [
      preset(`${m} sort`, () => sortTrace(m)),
      preset(`${m} with duplicates`, () => sortTrace(m, true)),
    ]),
    question(
      "Why keep key in a variable during insertion sort?",
      "Shifts overwrite its original array slot",
      "It makes the algorithm recursive",
      "The duplicated array values during shifting are temporary; key restores the saved value into the gap.",
    ),
  ),
  lesson(
    "merge",
    3,
    "Merge sort",
    "Split ranges, wait for both children, then merge two sorted runs.",
    "Recursion and half-open array ranges.",
    "Both input runs are sorted before a merge; take left first on equality.",
    "Θ(n log n) time for this version; Θ(n) auxiliary buffer plus O(log n) recursive depth.",
    "Do not merge a parent before both child calls have finished.",
    [preset("Four values", mergeTrace)],
    question(
      "Why take the left value first on a tie?",
      "To preserve stability",
      "To reduce the number of levels",
      "Equal items keep their original relative order when the left run wins ties.",
    ),
  ),
  lesson(
    "partition",
    3,
    "Quicksort partition",
    "Follow the boundary between <= pivot and > pivot regions.",
    "Array swaps and recursive divide-and-conquer.",
    "Before boundary: <= pivot. Between boundary and j: > pivot. The pivot reaches its final index.",
    "One partition Θ(n), O(1) extra space. Full quicksort expected Θ(n log n), worst Θ(n²); this last-pivot scheme degrades on equal/sorted input.",
    "Partitioning is not the same as sorting both sides. The demo intentionally shows one partition.",
    [
      preset("Mixed values", () => partitionTrace()),
      preset("All equal", () => partitionTrace(true)),
    ],
    question(
      "After partition, are both sides completely sorted?",
      "No, only their relation to the pivot is established",
      "Yes, partition sorts the array",
      "Quicksort must recurse on the two remaining regions.",
    ),
  ),
  lesson(
    "loops",
    4,
    "Counting loop work",
    "Derive exact counts before reducing to an asymptotic bound.",
    "Loop bounds, arithmetic series, and powers of two.",
    "Count a chosen basic operation over the actual iteration ranges.",
    "Linear Θ(n); triangular Θ(n²); doubling Θ(log n).",
    "Two nested loops do not automatically imply n²: their bounds and updates matter.",
    [
      preset("Linear count", () => loopTrace("linear")),
      preset("Triangular sum", () => loopTrace()),
      preset("Doubling index", () => loopTrace("doubling")),
    ],
    question(
      "How many increments occur in Σ(i), i=0…n−1?",
      "n(n−1)/2",
      "n² exactly",
      "The arithmetic series gives the exact count. Its leading term determines Θ(n²).",
    ),
  ),
  lesson(
    "recurrence",
    4,
    "Recurrence level work",
    "Sum work across recursion-tree levels, including leaves.",
    "Powers of two and recursive splitting.",
    "At each non-leaf level, number of nodes × subproblem size = n.",
    "The MODEL T(n)=2T(n/2)+n with T(1)=1 has Θ(n log n) work. The displayed function calculates that count; its own arithmetic runtime is Θ(n).",
    "Do not confuse the work-count function with an implementation that actually performs n operations at each node.",
    [preset("n = 8, powers of two", recurrenceTrace)],
    question(
      "How much modeled local work lies at each non-leaf level?",
      "n",
      "n²",
      "There are 2ᵈ nodes of size n/2ᵈ; multiplying cancels the depth factor.",
    ),
  ),
  lesson(
    "timing",
    4,
    "Timing ratios",
    "Solve for an unknown constant under an explicit growth model.",
    "Algebra and polynomial growth.",
    "Keep the algorithm, machine, and cost model fixed when scaling an estimate.",
    "Assumed quadratic growth only; this is a mathematical estimate, not a benchmark.",
    "A timing ratio is not proof of asymptotic complexity, especially for small inputs.",
    [preset("Triple a quadratic input", timingTrace)],
    question(
      "Under T(n)=c·n², tripling n multiplies time by what?",
      "9",
      "3",
      "The same constant cancels: (3n)²/n² = 9.",
    ),
  ),
  lesson(
    "bases",
    4,
    "Base conversion",
    "Build digits from quotient and remainder, then reverse their order.",
    "Unsigned division and remainder.",
    "Each saved remainder is the next least-significant digit.",
    "Θ(log_base value) divisions for positive value; one digit for zero.",
    "Reading remainders in encounter order reverses the numeral.",
    [preset("45 to binary", baseTrace)],
    question(
      "In what order are remainder digits produced?",
      "Least significant first",
      "Most significant first",
      "Each division removes the low digit, so the output must be read backward.",
    ),
  ),
  lesson(
    "bits",
    4,
    "Bit operations & subsets",
    "Treat bit positions as set membership and compare masks.",
    "Binary representation and unsigned integers.",
    "Bit i represents element i; masks select specific memberships.",
    "Fixed-width unsigned bit operations are constant time in this model.",
    "Use unsigned operands and valid shift counts; C integer width is not inferred from the display.",
    [preset("Five-element subsets", bitsTrace)],
    question(
      "Which operation keeps only elements present in both sets?",
      "Bitwise AND",
      "Bitwise XOR",
      "AND intersects sets; OR unions them; XOR selects membership in exactly one.",
    ),
  ),
];

export const lessons = catalog.map((entry, index) => ({
  ...entry,
  checkpoint:
    index % 2 === 0
      ? entry.checkpoint
      : {
          ...entry.checkpoint,
          choices: [...entry.checkpoint.choices].reverse(),
          answer: 1,
        },
}));
